backend:
  name: github
  repo: woolball/portfolio
  branch: main
  auth_scope: repo
  app_id: Iv23lid9Tcz05NLDUB7z
  base_url: https://woolball.github.io/portfolio/
media_folder: static/images/uploads
public_folder: /images/uploads
collections:
  - name: pages
    label: Pages
    folder: content
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
